# -*- coding: utf-8 -*-
"""draw_ow_pie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBL8xAl3ZJxNNk9Telil6jc9g6FE-ArP
"""

import matplotlib.pyplot as plt

pos_count = 11531  # 긍정 리뷰 수
neg_count = 11177  # 부정 리뷰 수


labels = [f'Positive (Thumbs Up)\n({pos_count:,}건)',
          f'Negative (Thumbs Down)\n({neg_count:,}건)']
sizes = [pos_count, neg_count]
colors = ['#48dbfb', '#ff6b6b'] # 긍정(파란색), 부정(빨간색)
explode = (0.03, 0)


plt.figure(figsize=(9, 9))


patches, texts, autotexts = plt.pie(sizes,
                                     explode=explode,
                                     labels=labels,
                                     colors=colors,
                                     autopct='%1.1f%%',
                                     startangle=140,
                                     shadow=True,
                                     textprops={'fontsize': 14, 'fontweight': 'bold'})


for autotext in autotexts:
    autotext.set_color('white')
    autotext.set_fontsize(16)


plt.title('Public Sentiment: Overwatch (English Reviews)', fontsize=18, fontweight='heavy', pad=20)


output_image = 'ow_sentiment_pie.png'
plt.savefig(output_image, dpi=300, bbox_inches='tight')

print(f"🎉 새로운 오버워치 단독 파이 차트가 저장되었습니다: {output_image}")