# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBL8xAl3ZJxNNk9Telil6jc9g6FE-ArP
"""

import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import matplotlib.pyplot as plt

nltk.download('vader_lexicon', quiet=True)


df_raw = pd.read_csv('ow2_steam_50k_raw.csv')
df_sample = df_raw.sample(n=3000, random_state=42).copy()
print("✅ 원본 데이터에서 3,000건 샘플링 완료.")

sia = SentimentIntensityAnalyzer()


def rule_based_labeling(row):
    text = str(row['review'])
    voted_up = row['voted_up']

    words = text.split()


    if len(words) < 4:
        return 'Irrelevant'


    score = sia.polarity_scores(text)['compound']


    if -0.15 <= score <= 0.15:
        return 'Neutral'
    if (voted_up and score < -0.15) or (not voted_up and score > 0.15):
        return 'Neutral'


    if voted_up and score > 0.15:
        return 'Positive'
    if not voted_up and score < -0.15:
        return 'Negative'

    return 'Irrelevant'


print("⚙️ 파이썬 VADER 기반 4클래스 라벨링 진행 중...")
df_sample['multi_label'] = df_sample.apply(rule_based_labeling, axis=1)


output_file = 'ow_4class_labeled_3k.csv'
df_sample.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"💾 라벨링 완료! 파일 저장됨: {output_file}")

=
label_counts = df_sample['multi_label'].value_counts()
print("\n📊 각 클래스별 데이터 분포 결과:")
print(label_counts)

plt.figure(figsize=(10, 6))
# 색상: 부정(빨강), 긍정(파랑), 중립(회색), 관계없음(노랑)
colors = {'Negative': '#ff6b6b', 'Positive': '#48dbfb', 'Neutral': '#a5b1c2', 'Irrelevant': '#fed330'}


bars = plt.bar(label_counts.index, label_counts.values, color=[colors[x] for x in label_counts.index], edgecolor='black', width=0.6)


for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2.0, yval + 10, f'{yval:,}', ha='center', va='bottom', fontsize=12, fontweight='bold')

plt.title('Distribution of 4-Class Labeled Overwatch Reviews (Sample: 3,000)', fontsize=16, fontweight='bold', pad=20)
plt.ylabel('Number of Reviews', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

# 이미지 파일로 저장
img_filename = 'ow_4class_distribution.png'
plt.savefig(img_filename, dpi=300, bbox_inches='tight')
print(f"\n🎉 4클래스 분포 그래프가 저장되었습니다: {img_filename}")