# -*- coding: utf-8 -*-
"""ow_review_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBL8xAl3ZJxNNk9Telil6jc9g6FE-ArP
"""

import pandas as pd
import re
import sys

file_name = 'ow2_steam_50k_raw.csv'
try:
    df = pd.read_csv(file_name)
    print(f"원본 데이터 로드 완료! 총 {len(df)}건")
except FileNotFoundError:
    print(f" 파일을 찾을 수 없습니다. 파일명을 확인해 주세요: {file_name}")
    sys.exit()


def clean_text(text):
    if not isinstance(text, str):
        return ""

    text = re.sub(r'[^a-zA-Z0-9\s.,!?\'\"]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

print("\n🧹 텍스트 클리닝을 시작합니다...")
df['clean_review'] = df['review'].apply(clean_text)


df['word_count'] = df['clean_review'].apply(lambda x: len(x.split()))
df_clean = df[df['word_count'] >= 4].copy()


df_clean['label'] = df_clean['voted_up'].astype(int)


df_final = df_clean[['review_id', 'clean_review', 'word_count', 'playtime_forever', 'label']]
output_filename = 'ow_steam_cleaned.csv'
df_final.to_csv(output_filename, index=False, encoding='utf-8-sig')

total_cleaned = len(df_final)
positive_count = len(df_final[df_final['label'] == 1])
negative_count = len(df_final[df_final['label'] == 0])
pos_ratio = (positive_count / total_cleaned) * 100
neg_ratio = (negative_count / total_cleaned) * 100

print("-" * 50)
print(f"전처리 후 살아남은 유효 데이터: {total_cleaned}건")
print(f" 긍정 리뷰: {positive_count}건 ({pos_ratio:.1f}%)")
print(f" 부정 리뷰: {negative_count}건 ({neg_ratio:.1f}%)")
print("-" * 50)

