# -*- coding: utf-8 -*-
"""ow_steam_review_50K.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBL8xAl3ZJxNNk9Telil6jc9g6FE-ArP
"""

import requests
import pandas as pd
import time
import sys

def get_ow_reviews(appid, max_reviews=50000):
    print(f"\n[Overwatch 2] 스팀 리뷰 단독 수집 시작 (목표: {max_reviews}건)")
    reviews_list = []
    cursor = '*'

    params = {
        'json': 1,
        'filter': 'recent',
        'language': 'english',
        'review_type': 'all',
        'purchase_type': 'all',
        'num_per_page': 100
    }

    while len(reviews_list) < max_reviews:
        params['cursor'] = cursor
        url = f"https://store.steampowered.com/appreviews/{appid}"

        try:
            response = requests.get(url, params=params, timeout=10)

            if response.status_code != 200:
                print(f"\n⚠️ 응답 지연 (Status {response.status_code}). 3초 대기...")
                time.sleep(3)
                continue

            data = response.json()

            if not data.get('reviews'):
                break

            for r in data['reviews']:
                review_text = r['review'].strip()
                if not review_text:
                    continue

                reviews_list.append({
                    'review_id': r['recommendationid'],
                    'review': review_text,
                    'voted_up': r['voted_up'],
                    'playtime_forever': round(r['author']['playtime_forever'] / 60, 1),
                    'votes_up': r['votes_up']
                })

            next_cursor = data.get('cursor')
            if not next_cursor or next_cursor == cursor:
                break
            cursor = next_cursor

            sys.stdout.write(f"\r데이터 파싱 중... [현재 누적: {len(reviews_list)}건]")
            sys.stdout.flush()

            time.sleep(0.5)

        except Exception as e:
            print(f"\n네트워크 오류: {e}")
            break

    df = pd.DataFrame(reviews_list)


    df.drop_duplicates(subset=['review_id'], inplace=True)

    if len(df) > max_reviews:
        df = df.iloc[:max_reviews]

    print(f"\n실제 유효 데이터 수집 완료! 총 {len(df)}건 확보.")
    return df

if __name__ == "__main__":

    TARGET = 50000
    df_ow = get_ow_reviews(2357570, max_reviews=TARGET)


    output_filename = 'ow2_steam_50k_raw.csv'
    df_ow.to_csv(output_filename, index=False, encoding='utf-8-sig')

    print("-" * 50)
    print(f"🎉 오버워치 2 단독 5만 건 데이터셋 구축 성공! 파일명: {output_filename}")

